### PR TITLE
Keep all requirements consistent and up to date across ALL package managers

### LINKED ISSUE #28: Chromedriver issues on raspberry - unknown error: DevToolsActivePort file doesn't exist
I m trying to run it on my raspberry pi4 but it seems that it does not like the chromedriver.
I had to arg the chromedriver location and I also tried with the latest version from https://github.com/electron/electron/releases but with same results.

Any idea pls?

pi@raspberrypi:~/blinkist-scraper $ python3 blinkistscraper/__main__.py user pass --book https://www.blinkist.com/en/nc/reader/on-saudi-arabia-en --chromedriver /usr/bin/chromedriver
[18:30:10] INFO Starting scrape run...
[18:30:10] INFO Initialising chromedriver at /usr/bin/chromedriver...
Traceback (most recent call last):
  File "blinkistscraper/__main__.py", line 340, in <module>
    main()
  File "blinkistscraper/__main__.py", line 279, in main
    chromedriver_path=args.chromedriver,
  File "/home/pi/blinkist-scraper/blinkistscraper/scraper.py", line 81, in initialize_driver
    options=chrome_options,
  File "/home/pi/.local/lib/python3.7/site-packages/seleniumwire/webdriver/browser.py", line 86, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
  (Driver info: chromedriver=78.0.3904.108 (4b26898a39ee037623a72fcfb77279fce0e7d648-refs/branch-heads/3904@{#889}),platform=Linux 5.4.51-v7l+ armv7l)

### PR DESCRIPTION
**Pull request by rocketinventor**
**Updated**: Old text has been _italicized_ and ~~crossed out~~.

_The version number listed for `lxml` is not the newest one available (`4.6.2` for Python 3.9). The "==" operator forces pip to use `lxml` version `4.5.2`, even if that meant downgrading it. This causes errors for `lxml` if "Microsoft Visual C++ 14.0" is not installed (because it is needed for compiling)._

_Also, some packages like `certifi` always need to be up to date (for securities' sake)._ They can now be updated as desired, and will not have to be rolled back in order to install `blinkist-scraper`.

Furthermore, the package versions and requirements lists specified by `pyproject.toml`, `poetry.lock`, and `requirements.txt` are all different, creating fragmentation in regards to what is actually installed when following the instructions. 

~~Since it doesn't seem like any of these packages require a specific version, I have changed all of them to minimum version numbers (instead of _required_ ones) using the `>=` operator.~~

This pull request updates the `requirements.txt` to **exactly** match the requirements specified by `pyproject.toml` and adds in a new tool to keep them in sync. Also, it ditches the `poetry.lock` file which was causing conflict about what actually needs to be installed. **All the requirement specifications can now be kept in loc-step** (instead of different specifications in different files, as was the case before). Pip already knows how to install dependencies properly. Now it can do so without having to have its hands tied. No C++ compiler needed!*

*anymore

Closes #28

### CODE REVIEW

**Comment by leoncvlt** [comment]
The project uses [poetry](https://python-poetry.org/) for dependencies management, `requirements.txt` is actually generated from the poetry settings: https://python-poetry.org/docs/cli/#export

I think it would make more sense to make these changes on the `pyproject.toml` and keep one source of truth for the dependencies version

**Comment by rocketinventor** [comment]
Well, I thought that it was an issue from dependabot, but I checked now, and I can see that it only updated the .lockfile.

If the requirements.txt file is indeed being managed by Poetry, then I am not sure how to fix this issue...

Poetry doesn't seem to give any options about how the requirements.txt file is generated. 
Lxml and certifi are not specified directly as a requirement, but they are sub-dependencies.
The only dependencies listed on the pyproject.toml file are:

 _chromedriver-autoinstaller = "^0.2.2"
colorama = "^0.4.3"
EbookLib = "^0.17.1"
requests = "^2.24.0"
selenium = "^3.141.0"
selenium-wire = "^2.1.0"_ 


Therefore, I would be unsure of how to fix this issue with Poetry (other than to manually edit the file).

Please feel free to advise, or update any settings that might fix this.

**Comment by zwoele** [comment]
pip install leoncvlt

**Comment by leoncvlt** [comment]
Thanks @rocketinventor, this is a good way to go!

**Pull request merged**
